# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

#services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

parameters:
#    parameter_name: value

services:
    valid_authenticate:
        class: AppBundle\Security\ValidateLogin
        arguments: [@doctrine.orm.entity_manager, @security.password_encoder]
